Feature/homework 1
vitya-v7/Task1 pull request #3
Opened 2020-10-23 10:06 UTC by vitya-v7

Первое ДЗ. Нужен был облачный мак, так что сдаю вроде вовремя. Сейчас появился временный мак, но облачный все равно еще пригодится.

2020-10-26 06:48 UTC, korshunigor commented
Принято на проверку

2020-11-01 15:21 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +	func changeSelectedDataInView(type: PickerType, index: Int)
Приведи форматирование всего проекта в порядок

2020-11-01 15:22 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +class CarDetailView: UIViewController {
Не согласованность названия класса, это же viewController

2020-11-01 15:23 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +    var output: ICarDetailViewOutput?
Это хорошо, что ты использовал такую архитектуру проекта. Но view управлять должен Presenter

2020-11-01 15:23 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +		if output != nil && textField.tag != 3 && textField.tag != 6 {
Не ясно что значит 6 и 3, вынеси тогда в enum

2020-11-01 15:43 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +class CarDetailView: UIViewController {
Разбей это на два класса View и ViewController. Где в VC ты будешь добавлять view. И передать этот view презентеру

2020-11-01 15:48 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/PickerView.swift
> +class PickerView: UIViewController {
Опять ViewController в одном модуле. Разве это не отельный модуль?

2020-11-01 15:50 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/PickerView.swift
> +		return options!.count
options?.count ?? 0

2020-11-01 15:52 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +			view!.setViewModels(viewModels: convertModelsToViewModels(models: carModelsFiltered))
нужно использовать guard чтобы избавиться от "!". Посмотри по всему проекту таки проблемные места.

2020-11-01 15:53 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +		let pv = storyboard.instantiateViewController(withIdentifier: "PickerViewIdentifier") as! PickerView
Отображение других модулей это работа роутера, а не презентера

2020-11-01 15:53 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +		self.view?.navigationController?.pushViewController(ModulesFactory.createCarDetailModule(key: carModelKey), animated: true)
Это должен делать роутер.

2020-11-01 15:53 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +		carService?.deleteCar(key: carModels![row].carKey!)
Эти вещи должен делать интерактор

2020-11-01 15:54 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/View/Cell/ViewModel/CarsElementViewModel.swift
> +struct CarsElementViewModel {
Проверь еще раз задание, там не все поля опциональные

2020-11-01 15:55 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/View/CarsListView.swift
> +class CarsListView: UIViewController, UITextFieldDelegate {
Такие же архитектурные проблемы что и в details

2020-11-01 15:57 UTC, Jinfaa commented on Task1/TestTaskCFT/CarsListModule/View/Cell/ViewModel/CarsElementViewModel.swift
> +struct CarsElementViewModel {
Это дубликат  CarDetailViewModel

2020-11-01 15:58 UTC, Jinfaa commented on Task1/TestTaskCFT/Services/Data/CarService.swift
> +	private func setCars(cars: [CarModel]) {
не нужно писать private внутри приватного расширения

2020-11-01 15:58 UTC, Jinfaa commented on Task1/TestTaskCFT/Services/Data/CarService.swift
> +		let encodedData =  try! JSONEncoder().encode(cars)
guard

2020-11-01 15:59 UTC, Jinfaa requested changes
Требуются правки

2020-11-05 15:29 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +		carService?.deleteCar(key: carModels![row].carKey!)
Это не VIPER архитектура, а MVP, где presenter выполняет роль роутера и интерактора

2020-11-05 15:29 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarsListModule/View/CarsListView.swift
> +class CarsListView: UIViewController, UITextFieldDelegate {
Это не VIPER архитектура, а MVP, где presenter выполняет роль роутера и интерактора

2020-11-05 15:32 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +    var output: ICarDetailViewOutput?
Он и так им управляет: в файле CarDetailPresenter есть свойство var view: ICarDetailViewInput?

2020-11-05 15:32 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarDetailModule/View/PickerView.swift
> +class PickerView: UIViewController {
Решил что такого поповера не стоит выделять отдельный модуль

2020-11-05 15:33 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +		self.view?.navigationController?.pushViewController(ModulesFactory.createCarDetailModule(key: carModelKey), animated: true)
Это не VIPER архитектура, а MVP, где presenter выполняет роль роутера и интерактора

2020-11-05 15:33 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarsListModule/Presenter/CarsListPresenter.swift
> +		let pv = storyboard.instantiateViewController(withIdentifier: "PickerViewIdentifier") as! PickerView
Это не VIPER архитектура, а MVP, где presenter выполняет роль роутера и интерактора

2020-11-05 15:47 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarDetailModule/View/CarDetailView.swift
> +class CarDetailView: UIViewController {
ViewController в MVP - это класс, который  содержит только логику отображения элементов(view) и получает данные от презентера(как у меня и сделано)

2020-11-05 15:50 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarsListModule/View/Cell/ViewModel/CarsElementViewModel.swift
> +struct CarsElementViewModel {
В данном случае да, так как в list модуле и detail модуле мы показывает одинаковую информацию/

2020-11-06 16:24 UTC, Jinfaa commented on Task1/TestTaskCFT/CarDetailModule/View/PickerView.swift
> +class PickerView: UIViewController {
Почему?

2020-11-06 16:29 UTC, Jinfaa reviewed
Разобраться с PickerView. А в остальном хорошо

2020-11-06 19:20 UTC, vitya-v7 commented on Task1/TestTaskCFT/CarDetailModule/View/PickerView.swift
> +class PickerView: UIViewController {
Имена класса и файла поменял. Потому что PickerViewController  - это View в mvp, и у PickerViewController итак уже есть презентер : 
var output: ICarDetailViewOutput?
var outputList: ICarsListViewOutput?
первый относится к детальному экрану, второй к табличному.

2020-11-07 02:34 UTC, Jinfaa approved these changes
можно мержить

2020-11-07 03:01 UTC, merged