Домашняя работа №3
vitya-v7/Task1 pull request #5
Opened 2020-11-03 11:29 UTC by vitya-v7

Приложение состоит из tabbarcontroller-а и трех экранов, разделенных на два файла: view и view controller. Весь UI и констрейнты делаются в коде, во вьюхах. 
1 и 3 экран имеет одинаковый набор констрейнтов для обеих ориентаций.
2 экран - разный, поэтому при альбомной и портретной ориентации разное разположение элементов.
Сдаю вовремя (на всякий случай))))

2020-11-03 17:00 UTC, GkFoxes commented
Принял на проверку, передаю другому преподавателю)

2020-11-09 18:07 UTC, korshunigor commented
Задание принято на проверку

2020-11-13 23:36 UTC, korshunigor requested changes
Замечаний не очень много, многие из них общие для всех присутствующих классов, по этому не стал их дублировать, после исправления еще раз отсмотрю работу

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/AppDelegate.swift
> +			let navigationController = UINavigationController(rootViewController: viewController)
А нужен ли нам UINavigationController в рамках данного ДЗ?

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Image.swift
> +    var image: UIImage {
Давай вычислимое свойство отделим от кейса одной пустой строкой

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Image.swift
> +        guard let image = UIImage(named: rawValue) else { assertionFailure(); return UIImage() }
Давай для более удобного чтения кода все что в блоке else разнесем по разным строкам

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/TabBarController/TabBarController.swift
> +public class TabBarController: UITabBarController {
1) public можно опустить, т.к. данный класс не выходит за пределы проекта с домашним заданием №3, а в пределах проекта он нам ни на что не влияет
2) В коде ниже пробелы вперемешку с табами

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/TabBarController/ViewControllers/ViewController1.swift
> +	var myView: View1 = View1(frame: .zero)
Тут сразу несколько моментов есть, на которые стоит обратить внимание:
1) Желательно отделят методы от свойств одной пустой строкой
2) В коде мы его ни как не меняем, по этому можно сделать приватной константой
3) Можно опустить явное указание типа `: View1` т.к. свойство сразу же инициализируются при объявлении

Они же относятся и к другим объектам

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/TabBarController/ViewControllers/ViewController1.swift
> +class ViewController1: UIViewController {
По заданию у нас экраны называются "Первый экран", "Второй экран", в коде же желательно использовать более интуитивные названия чем ViewController1, View1 и т.д., давай хотя бы назовем их хотя бы ThirdViewController, ThirdView и т.д.

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +	private enum Constants: CGFloat
Давай enum поднимем в самое начало, чтобы объявление свойств и констант были ближе друг к другу, использование rawValue не является ошибкой, но если заюзать static let вместо кейсов, то не придется везде дублировать обращение к .rawValue (и в других местах тоже)

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View3.swift
> +	private var isLayoutCompact = true
Не используется

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View3.swift
> +	var buttonBottomConstraint : NSLayoutConstraint?
private потерялся

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +	private var isLayoutCompact = true
Не используется

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +		super.traitCollectionDidChange(previousTraitCollection)
Если в методе происходит вызов только super метода, то можно его не оверайдить, а просто выпилить )

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +// MARK: Shared Layout
Не совсем понял почему это "Shared" и для чего эти методы вынесены в отдельный private extension?

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +	func setupViewsLayout() {
Давай удалим этот метод, мы те можем напрямую вызвать setupSharedLayout

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +		addSubview(activityIndicator)
Это не ошибка, но на всякий случай отмечу, обычно если подразумевается отображение индикации поверх чего-то, то добавляют ее непосредственно на этот объект, в данном случае на imageView, а не на self

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +			activityIndicator.widthAnchor.constraint(
Установку констрейнтов высоты и ширины можно опустить т.к. они не влияют на размер индикатора

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +		button1.layer.borderColor = .init(red: 1, green: 0, blue: 0, alpha: 1)
Немного информативнее будет, если использовать не `.init`, а указание типа `CGColor(red:...)`

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +	func setupViewsAppearances() {
В целом, можно немного изменить логику и поработать с неймингом т.к. он сейчас не очень информативен (во всяком случае что делают методы Appearances не понял пока не посмотрел реализацию).

Могу предложить несколько вариантов:
1) Логику находящуюся внутри методов "настройки отображения" вынести в инициализаторы объектов, например вместо setupLabel1Appearances можно сделать вот такой инициализатор:
```swift
private let label1: UILabel = {
    let label = UILabel()
    label.numberOfLines = 1
    label.textAlignment = .center
    label.text = "Simple Label"
    return label
}()
```
А методы отвечающие за настройку констрейнтов уже назвать как-то вроде configureSubviews и в частности configureLabel1

2) Имеющиеся методы настройки объектов назвать как "конфигураторы" (configureSubviews, configureLabel1 и т.д.) т.к. мы по сути настраиваем их отображение, а методы настройки констрейнтов уже назвать setupSubviewConstraints, setupLabel1Constraints, чтобы конкретизировать что именно настраивается

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View2.swift
> +			guard isLayoutCompact != false else { return }
Если переводить на русский, то это "Если является истинной то, что isLayoutCompact не является ложью", мне кажется можно упростить =)

Ну и схожую проверку стоит добавить выше

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View2.swift
> +
Давай везде выдерживать отступы не более чем в одну пустую строку

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View3.swift
> +		NSLayoutConstraint.activate([buttonBottomConstraint!])
Место потенциального краша из-за форсанврапа, думаю стоит в начале метода поставить guard, в случае ошибки вызвать assertionFailure с сообщением что именно пошло не так

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View3.swift
> +				textField.text = updatedText
В итоге введенное пользователем значение теряется?)
У UITextField есть свойство isSecureTextEntry, которое позволяет скрыть вводимое пользователем значение

2020-11-13 23:36 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/View3.swift
> +				multiplier: 0.10)
По хорошему такие числа стоит тоже выносить в константы

2020-11-21 20:50 UTC, vitya-v7 commented on Task3/Task3/Views/ViewsForTabBarController/View1.swift
> +// MARK: Shared Layout
Shared в View1 и View3 удалил. ну private extension, чтобы как-то визуально оградить методы с разным назначением. Может и не лучший вариант, но не знаю как лучше.

2020-11-21 21:44 UTC, vitya-v7 commented
Прошу прощения, что так долго.

2020-11-21 23:40 UTC, vitya-v7 commented
Сделал кое-какие кульбиты, так как гит не перестает удивлять

2020-11-23 15:46 UTC, korshunigor requested changes
Почти все замечания являются общими (актуальны для всех экранов), не стал дублировать в каждом месте где их можно применить. Отсмотри пожалуйста весь проект при их исправлении.

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Image.swift
> +			assertionFailure(); return UIImage()
Лучше разнести по разным строкам, а в assertionFailure добавить описание что пошло не так

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Image.swift
> +		else {
Лучше поднять else на предыдущую строку, т.к. само условие весьма не больше

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +class FirstView: UIView {
Почти все методы можно вынести в приватное расширение, чтобы они не торчали наружу

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +		button2.layer.borderWidth = 1
Подобные значения стоит вынести в константы

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +	private struct Constants
Давай заменим на enum, чтобы не было соблазна потом где-то в коде создавать экземпляр `let constants = Constants()` ))

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +		guard let animationDuration = userInfo[UIResponder.keyboardAnimationDurationUserInfoKey] as? NSValue else {return}
1) потерялись пробелы перед и после `return`
2) Т.к. обработка ложности этих условий одинаковая, немного лучше будет объединить их в один `guard`:
```swift
guard let userInfo = notification.userInfo,
      let keyboardSize = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue,
      let animationDuration = userInfo[UIResponder.keyboardAnimationDurationUserInfoKey] as? NSValue 
else {
      return
}
```

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +		ThirdView.animate(withDuration: animationDuration as! TimeInterval, animations: {
1) А зачем мы кастим `animationDuration` в NSValue, а затем в `TimeInterval`, если мы можем сразу кастануть его в `TimeInterval`?
2) Сегодня все работает как задумано, а завтра Apple выкатывает обновление, наш `as!` зафейлится и пользователь не сможет продолжить работать приложением из-за краша связанного с анимацией, это прям очень не очень, лучше извлекать значение безопасно

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +		})
Можно упростить убрав передачу анимации как параметр:
```swift
ThirdView.animate(withDuration: animationDuration) {
    NSLayoutConstraint.deactivate([self.buttonBottomConstraint!])
    self.setButtonBottomConstraint(space: keyboardMinusTabBarHeight)
    self.layoutIfNeeded()
}
```

2020-11-23 15:46 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +			NSLayoutConstraint.deactivate([self.buttonBottomConstraint!])
В один прекрасный момент у нас будет отсутствовать `buttonBottomConstraint` и мы упадем, почему бы не извлечь значение заранее?

2020-11-24 05:28 UTC, vitya-v7 commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +	private struct Constants
решил сделать Синглетон, так как в энуме не могут повторяться одинаковые числа под разными кейсами.

2020-11-25 18:25 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +	private struct Constants
И в итоге мы вообще из любого места приложения можем обратиться к константам, которые относятся к конкретному экрану? Из методов работы с API, из работы с БД, из экрана 10... Это мягко говоря не очень. Синглтоны вообще очень сомнительная штука, которой лучше не злоупотреблять.

1) Константы относящиеся к конкретному экрану должны быть доступны только этому экрану, ни как иначе
2) Все константы можно расположить внутри enum-а, просто нужно использовать не кейсы с rawValue, а `static let`, тогда ты сможешь и одинаковые числа присваивать и даже использовать разные типы данных

2020-11-25 18:32 UTC, korshunigor requested changes
Давай поправим еще пару замечаний

2020-11-25 18:32 UTC, korshunigor commented on Task3/Task3/Constants/Constants.swift
> +//  Constants.swift
Этот файл выпилить, избавиться от синглтонов, переделать все обратно на `enum Constants` и сделать их приватными для тех экранов, к которым они относятся

2020-11-25 18:32 UTC, korshunigor commented on Task3/Task3/Constants/Constants.swift
> +	let borderButton1Color: CGColor = UIColor.systemRed.cgColor
В данном случае работает выведение типа из контекста, можно записать так:
```swift
let backgroundButton1Color = UIColor.cyan
let borderButton1Color = UIColor.systemRed.cgColor
```
Ниже и в ThirdViewConstants аналогично

2020-11-25 18:32 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +	public override init(frame: CGRect) {
А для чего тут public?

2020-11-25 18:32 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/SecondView.swift
> +	public override init(frame: CGRect) {
Для чего тут public?

2020-11-25 18:32 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/SecondView.swift
> +	func configureTitleLabel() {
Давай выдерживать отступ в 1 пустую строку

2020-11-25 18:32 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +	public override init(frame: CGRect) {
Для чего тут public?

2020-11-26 20:27 UTC, korshunigor requested changes
В проекте сломана ссылка на папку. Если она не нужна, то ее нужно удалить из проекта
<img width="273" alt="Снимок экрана 2020-11-26 в 23 17 05" src="https://user-images.githubusercontent.com/17854702/100389606-e26f9080-303e-11eb-9f15-ff28557c8971.png">

2020-11-26 20:27 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +	private var Constraints: [NSLayoutConstraint] = []
1) Наименование свойств с маленькой буквы
2) Есть вызов активации констрейнтов, но нет заполнения этого массива, по этому его можно выпилить

2020-11-26 20:27 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/FirstView.swift
> +	private var regularConstraints: [NSLayoutConstraint] = []
Не используются, можно выпилить

2020-11-26 20:27 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +	private var Constraints: [NSLayoutConstraint] = []
Наименование свойств с маленькой буквы

2020-11-26 20:27 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +				self.setButtonBottomConstraint(space: 0)
Нолик тоже константа, давай вынесем его, к тому же это значение несколько раз в этом классе используется

2020-11-27 12:10 UTC, korshunigor approved these changes
Аппрув ставлю, но перед мерджем поправь пожалуйста отступы и guard (то что комменты отписал)

2020-11-27 12:10 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +        guard let animationDuration = userInfo[UIResponder.keyboardAnimationDurationUserInfoKey] as? TimeInterval else { return }
Тут табы вперемешку с пробелами, желательно отступы делать либо везде табами, либоо везде пробелами. Конкретно в данном случае у нас обработка провала выполнения этих действий одинаковая, по этому можно объединить в один guard:
```swift
guard let userInfo = notification.userInfo,
      let animationDuration = userInfo[UIResponder.keyboardAnimationDurationUserInfoKey] as? TimeInterval 
else { return }
```

2020-11-27 12:10 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +		let keyboardFrame = keyboardSize.cgRectValue
Табы вперемешку с пробелами

2020-11-27 12:10 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +	}
Табы вперемешку с пробелами

2020-11-27 12:10 UTC, korshunigor commented on Task3/Task3/Views/ViewsForTabBarController/ThirdView.swift
> +	}
Табы вперемешку с пробелами

2020-11-28 03:04 UTC, merged