Домашнее задание №4
vitya-v7/Task1 pull request #6
Opened 2020-11-10 11:27 UTC by vitya-v7

Задание выполнено в коде. Реализован SplitViewController с таблицей на master view controller и детальными представлениями элемента в detail view controller.

2020-11-10 11:27 UTC, vitya-v7 commented
Задание выполнено вовремя)))

2020-11-10 15:11 UTC, noreasonwhyiamhere commented
Задание принято на проверку)

2020-11-10 15:13 UTC, noreasonwhyiamhere commented
добавь плиз в ревьюверы Viscount88

2020-11-10 15:32 UTC, vitya-v7 commented
> добавь плиз в ревьюверы Viscount88

он у меня не добавился почему-то, хотя я его добавлял

2020-11-10 16:21 UTC, noreasonwhyiamhere commented
@Viscount88 можешь плиз принять приглос + возьми в ревью)

2020-12-09 18:06 UTC, Viscount88 requested changes
Качественная работа, но есть замечания. Давай поправим - будет отлично.

2020-12-09 18:06 UTC, Viscount88 commented on Task4/Task4/Controllers/DetailViewController/DetailView.swift
> +	func configure(object: CellModel?) {
Это не критично, но если метод принимает на вход опционал - значит опционал ему должен быть нужен. У тебя в случае нила метод не делает ничего, поэтому логичнее наверное проверить модель на нил, а потом уже передавать её в этот метод без опционала.

2020-12-09 18:06 UTC, Viscount88 commented on Task4/Task4/Controllers/DetailViewController/DetailViewController.swift
> +		myView.configure(object: object)
Может я что-то упускаю, а зачем ты тут конфигуришь вью? У тебя тут обджект всегда нил, метод ничего не делает. Если я прав - то тебе не нужен обджект в параметрах класса вообще. Ну и передаваться он тогда будет без опционала. А даже если не прав - то лучше тут от опционала избавиться и в метод отдать обязательный обджект.

2020-12-09 18:06 UTC, Viscount88 commented on Task4/Task4/Controllers/MasterViewController/DataSource/MasterTableViewDataSource.swift
> +		return cellAccepted!
Ну нет. Если уж ты пошёл таким путем - пройдись гвардом, если всё есть собери свою ячейку, а если нет - выдай дефолтную  TableViewCell, не надо тут никаких форс анврапов.

2020-12-09 18:06 UTC, Viscount88 commented on Task4/Task4/Views/Cells/MainCell.swift
> +		selectedBackgroundView!.backgroundColor = UIColor.systemGreen
Во-первых, не используй "!" - force unwrap. Во-вторых, тут можно насколько я помню просто через selectedBackgroundView?. ... Если её нет - то и цвет ей не нужен, к чему тут форсить.

2020-12-11 12:06 UTC, vitya-v7 commented on Task4/Task4/Controllers/DetailViewController/DetailViewController.swift
> +		myView.configure(object: object)
Да, ты прав. Item в этом файле меняется только при пуше детального экрана (setItem - функция), так что во viewWillAppear - совсем лишний код. И насчет проверти object в этом же классе - он просто лишний.

2020-12-11 12:33 UTC, vitya-v7 commented on Task4/Task4/Controllers/MasterViewController/DataSource/MasterTableViewDataSource.swift
> +		return cellAccepted!
тут каждая ячейка соберется 100% без всяких анврапов, т.к массив cellModels неопциональный, т.к мы заранее знаем данные и создаем его в методе mockData. А все остальные "!" убрал, их вставил по глупости.

2020-12-22 03:30 UTC, Viscount88 approved these changes
Хорошая работа

2020-12-22 03:30 UTC, Viscount88 commented on Task4/Task4/Controllers/DetailViewController/DetailViewController.swift
> +		//forced unwrapping (!), потому что я в первой строке метода присвоил object неопциональный item
неактуальный коммент?

2020-12-22 03:35 UTC, vitya-v7 commented on Task4/Task4/Controllers/DetailViewController/DetailViewController.swift
> +		//forced unwrapping (!), потому что я в первой строке метода присвоил object неопциональный item
Просто пояснение на всякий случай

2020-12-22 03:36 UTC, merged